[package]
name = "simple-http-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shs"
path = "src/bin/main.rs"

[dependencies]
log = "0.4.21"
pretty_env_logger = "0.5.0"
regex = "1.10.4"
once_cell = "1.19.0"
