#!/bin/sh /etc/rc.common
 
USE_PROCD=1
APP=rust-simple-http-server
start_service(){ 
    procd_open_instance 
    procd_set_param command /usr/bin/$APP
    procd_set_param respawn
    procd_set_param env RUST_BACKTRACE=1
    procd_set_param env RUST_LOG=info
    procd_set_param file /etc/config/$APP
    procd_set_param stdout 1
    procd_set_param stderr 1 
    procd_close_instance
}
